import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
//
import Sidebar from "@/components/layout/Sidebar";
import FollowBar from "@/components/layout/FollowBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <main className="flex min-h-screen flex-col items-center justify-between px-24"> */}
        <div className="container h-full mx-auto xl:px-30 max-w-6xl">
          <div className="grid  grid-cols-4 h-full">
            <Sidebar />
            <div
              className="
              col-span-3 
              lg:col-span-2 
              border-x-[1px] 
              border-neutral-800
          "
            >
              {children}
            </div>
            <FollowBar />
          </div>
        </div>
        {/* </main> */}
      </body>
    </html>
  );
}
